### ISSUE TITLE
'master' branch; request to rename to 'main' 

### ISSUE THREAD

**Issue by johnbent** [vvv/dotfiles#2]
Hey @vvv , looks like somehow your personal github is linked from CORTX somewhere.  I'm not sure where/how but Sanjog was asking me about it.  It's your personal github but it might be nice for you to voluntarily rename 'master' to 'main'.  Thanks for considering this!

**Comment by vvv** [comment]
@johnbent Thanks for your input.

I won't rename the branch now, but I'll think over your suggestion.

Please send my regards to Sanjog.
